---
title: "UMDDC"
author: "Logan Robert McGuire"
date: "February 20, 2021"
output: html_document
---

```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(stats4)
library(vcd)
library(fitdistrplus)
library(binom)

covid.data = read.csv("Data_Lv2_NCSG_BehaviorChangesCOVID19.csv")
ages.covid = as.numeric(covid.data$Age)
```

```{r}
hist(ages, xlab="Age (Years)", 
     main = "Age of Respondents", breaks = 10, freq = FALSE, xlim = c(0,100))
```

```{r}
covid_males <- covid.data %>%
  filter(Sex == '1')
covid_females <- covid.data %>%
  filter(Sex == '2')
covid_married <- covid.data %>%
  filter(Married == '2')
covid_unmarried <- covid.data %>%
  filter(Married != '2')

age_married = as.numeric(covid_married$Age)
age_unmarried = as.numeric(covid_unmarried$Age)

#overlay over eachother

```

```{r}
plot1 = hist(age_married, xlab="Age (Years)", 
     main = "Age of Married Respondents", breaks = 10, freq = FALSE, xlim = c(0,100))
plot2 = hist(age_unmarried, xlab="Age (Years)", 
     main = "Age of Unmarried Respondents", breaks = 10, freq = FALSE, xlim = c(0,100))
married.covid = as.numeric(covid.data$Married)
boxplot(ages.covid~married.covid, data=pbp, main="Age By Maritial Status", xlab="Marital Status", ylab="Age", col="steelblue", border="black")
```

